import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        "border-hover": "hsl(var(--border-hover))",
        "border-faint": "hsl(var(--border-faint))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        surface: "hsl(var(--surface))",
        "surface-2": "hsl(var(--surface-2))",
        faint: "hsl(var(--faint))",
        subtle: "hsl(var(--subtle))",
        "metric-value": "hsl(var(--metric-value))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          hover: "hsl(var(--primary-hover))",
          fill: "hsl(var(--primary-fill))",
          "fill-border": "hsl(var(--primary-fill-border))",
          "fill-text": "hsl(var(--primary-fill-text))",
        },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        status: {
          "red-text": "hsl(var(--status-red-text))",
          "red-fill": "hsl(var(--status-red-fill))",
          "amber-text": "hsl(var(--status-amber-text))",
          "amber-fill": "hsl(var(--status-amber-fill))",
          "blue-text": "hsl(var(--status-blue-text))",
          "blue-fill": "hsl(var(--status-blue-fill))",
          "green-text": "hsl(var(--status-green-text))",
          "green-fill": "hsl(var(--status-green-fill))",
          "gray-text": "hsl(var(--status-gray-text))",
          "gray-fill": "hsl(var(--status-gray-fill))",
        },
      },
      fontSize: {
        "10": "10px", "11": "11px", "12": "12px", "13": "13px", "14": "14px", "24": "24px",
      },
      borderRadius: { lg: "var(--radius)", md: "7px", sm: "5px" },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "spin-slow": { to: { transform: "rotate(360deg)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
